#ifndef STATES_H
#define STATES_H

#define STATE_INIT 1
#define STATE_BROAD_SEARCH 2
#define STATE_MOVE_TO_BALL 3
#define STATE_ROTATE_SEARCH 4
#define STATE_MOVE_TO_SEARCH 5
#define STATE_CHECK_BALL_AT_TARGET 6
#define STATE_REFINE_POSITION 7
#define STATE_BALL_READY_TO_PICK 8
#define STATE_GRAB_BALL 9
#define STATE_LOCATE_GOAL 10
#define STATE_REFINE_GOAL_POS 11
#define STATE_DROP_BALL_AT_GOAL 12
#define STATE_SEARCH_MISSED_BALLS 13
#define STATE_ERROR 0

static int control_state;

#endif